baseURL = "https://ton-nom-de-domaine.com/"
defaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "Anthony David"
theme = "PaperMod"
defaultContentLanguageInSubdir = true  # important pour URL type /fr/, /en/

[languages]

[languages.fr]
  languageName = "🇫🇷"
  weight = 1
  title = "Anthony David"
  contentDir = "content/fr"

[languages.en]
  languageName = "🇬🇧"
  weight = 2
  title = "Anthony David"
  contentDir = "content/en"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "À propos"
    url = "/fr/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projets"
    url = "/fr/projects/"
    weight = 2

[params]
  homeInfoParams = false
